project_name: shorturl
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
archives:
  - replacements:
      linux: linux
      386: i386
      amd64: amd64
    name_template: "{{ .Binary }}.{{ .Version }}-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README*'
      - '.github'
